api:
  api_key: lmstudio
  api_type: openai-compatible
  base_url: http://localhost:1234/v1
  model: openai/gpt-oss-20b
assignment:
  output_1: data/output/news_sample_25__prompt__IPTC_seed_2/assignment_lvl1.jsonl
  prompt: prompt/assignment.txt
config_id: news_sample_25__prompt__IPTC_seed_2
data_sample: data/input/news_sample_25.jsonl
generation:
  output: data/output/news_sample_25__prompt__IPTC_seed_2/generation_1.jsonl
  prompt: prompt/generation_1.txt
  seed: data/pre_generated_topic_lists/seeds/IPTC_seed_2.md
  topic_output: data/output/news_sample_25__prompt__IPTC_seed_2/generation_1.md
verbose: true
